/*
 * @author Dariusz Chmiela
 * @date 2016-09-09
 * @description BTN_BuilderHelper interface methods and fields for all builders
*/
public interface BTN_BuilderHelper {
    /**
     * @author Dariusz Chmiela
     * @date 2016-09-09
     * @description get Method gets building record
     * @return Object building record
    */
    Object get();
    /**
     * @author Dariusz Chmiela
     * @date 2016-09-09
     * @description save Method saves building record
     * @return Object building record
    */
    Object save();
}