public class BTN_OpportunityLineItemWrapper {
	/*public OpportunityLineItem lineItem{set; get;}
	public Product2 product{set; get;}
	public transient PricebookEntry entry{set; get;}
	public String price{set; get;}
	public Integer rowNum{set; get;}

	public BTN_OpportunityLineItemWrapper(OpportunityLineItem lineItem, Product2 product, PricebookEntry entry) {
		this.lineItem = lineItem;
		this.product = product;
		this.entry = entry;
	}

	public BTN_OpportunityLineItemWrapper() {}*/
}