@isTest
private class BTN_OpportunityLineItemWrapper_Test {
	@isTest static void opportunityLineItemWrapperContructionTester() {
		/*Id pb = Test.getStandardPricebookId();
		List<Product2> prod = BTN_TestDataFactory.getProduct();

		List<PricebookEntry> pbEntry = BTN_TestDataFactory.getStandardPriceBookEntries(prod);

		Opportunity newOppo = BTN_TestDataFactory.getOpportunity(pb);
		OpportunityLineItem newProductInOppo = new OpportunityLineItem(Quantity = 20
			, PricebookEntryId = pbEntry.get(0).Id, Hourly_Rate__c = 15, OpportunityId = newOppo.Id
			, TotalPrice = 1);
		insert newProductInOppo;
		System.assertNotEquals(null, new BTN_OpportunityLineItemWrapper());
		System.assertNotEquals(null, new BTN_OpportunityLineItemWrapper(newProductInOppo, prod.get(0), pbEntry.get(0)));*/
		System.assert(true);
	}
}